services:
  - type: web
    name: collaborative-canvas-server
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server/server.js"
    envVars:
      - key: NODE_VERSION
        value: 22


